### PR TITLE
Feat: added Badges component

### PR DESCRIPTION
**Pull request by Richa-rani02**

### CODE REVIEW

**Comment by spraveenofficial** [comment]
Looks good :)

**Review by abhijeetekad — APPROVED** [review]
This looks great.

**Comment by abhijeetekad** [comment]
you can put a screenshot of the output in description so that it will be easy to review code.

**Comment by Richa-rani02** [comment]
> you can put a screenshot of the output in description so that it will be easy to review code.
 sure will add it from now ownwards.

**Pull request merged**
